apiVersion: v1
kind: service
metadata:
  name: product-service
spec: 
  type: ClusterIP
  selector:
    app: product-service
    ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
    